import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
// Note the curly braces here: { Providers }
import { Providers } from '@/lib/providers';
import { Toaster } from "sonner";
// toaster for showing messages to user anywhere in the app


const geistSans = Geist({ 
  variable: "--font-geist-sans", 
  subsets: ["latin"], 
});

const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono", 
  subsets: ["latin"], 
});

export const metadata: Metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrapping children in your Providers component */}
        <Providers>
          {children}
          {/* toaster will be available on every page */}
          <Toaster position="top-center" richColors/>
        </Providers>
      </body>
    </html>
  );
}
